added the new twitter logo(x)
linux-club-dev/linux-club-web pull request #13
Opened 2024-02-22 12:28 UTC by akshaykaluse35

This pull request introduces the updated Twitter logo(x) to the project. The new logo(x) enhances brand representation and aligns with the latest design guidelines provided by Twitter. The changes include updating the logo(x) asset files and integrating them into the project's codebase.

Changes:

    Added the new Twitter logo(x) asset files.
    Updated references to the Twitter logo(x) in relevant project files.
    Ensured consistency with the project's design standards.

Reasoning:
Keeping the project up-to-date with the latest branding assets is essential for maintaining a cohesive user experience. By incorporating the new Twitter logo(x), we ensure that our application remains visually appealing and in line with current design trends.

Testing:

    Verified that the new Twitter logo(x) displays correctly across various screen resolutions.
    Checked for any rendering issues or distortions caused by the logo(x) update.
    Tested logo(x) accessibility and visibility on different backgrounds and themes.
![Uploading Screenshot from 2024-02-22 17-57-59.png…]()
![Uploading Screenshot from 2024-02-22 17-57-55.png…]()

2024-02-22 18:34 UTC, shubham-kshetre commented
Hello @akshaykaluse35, The preview of your PR is working fine. But, icon changed by you seems to be blank to me. PTAL!

2024-02-22 18:36 UTC, shubham-kshetre commented
Also, Please do changes in your forked repository instead of organization repository

2024-02-22 20:01 UTC, akshaykaluse35 commented
@shubham-kshetre I've tested it and it works fine for my end

2024-02-22 20:02 UTC, akshaykaluse35 commented
@shubham-kshetre yeah sure ;) next time i'll make changes to forked repo

2024-02-23 09:17 UTC, shubham-kshetre commented
@akshaykaluse35 can you PTAL for why icon is not visible in the commit?

2024-03-03 18:35 UTC, shubham-kshetre commented
@SAYUK09 PTAL

2024-03-04 14:26 UTC, SAYUK09 requested changes

2024-03-04 14:26 UTC, SAYUK09 commented on package.json
> +    "@next/bundle-analyzer": "^12.3.4",
Why is there a change in package.json file?
Did you install any packages ?

2024-03-15 05:38 UTC, akshaykaluse35 commented on package.json
> +    "@next/bundle-analyzer": "^12.3.4",
I haven't installed any packages.... Thank You ;)

2024-03-15 05:43 UTC, shubham-kshetre approved these changes

2024-03-15 12:50 UTC, SAYUK09 approved these changes

2024-03-15 12:52 UTC, merged